/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author longs
 */
public class ThemSV extends javax.swing.JFrame {

    /**
     * Creates new form ThemSV
     */
    public ThemSV() {
        initComponents();
        this.setLocation(960-this.getSize().width/2,300);
        radnam.setSelected(true);
        btnsua.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtHten = new javax.swing.JTextField();
        txtNsinh = new javax.swing.JTextField();
        txtTenLop = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        radnam = new javax.swing.JRadioButton();
        radNu = new javax.swing.JRadioButton();
        txtMaLop = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        txtKhoaS = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtMk = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnTSV = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MSSV");

        jLabel2.setText("Họ và Tên");

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Tên Lớp");

        jLabel6.setText("Mã Lớp");

        jLabel7.setText("Khóa");

        jLabel8.setText("Khoa");

        jLabel9.setText("Mật Khẩu");

        txtMSSV.setForeground(new java.awt.Color(153, 153, 153));
        txtMSSV.setText("B1234567");
        txtMSSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMSSVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMSSVFocusLost(evt);
            }
        });

        txtHten.setForeground(new java.awt.Color(153, 153, 153));
        txtHten.setText("Nguyễn Văn A");
        txtHten.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHtenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHtenFocusLost(evt);
            }
        });

        txtNsinh.setForeground(new java.awt.Color(153, 153, 153));
        txtNsinh.setText("yyyy-mm-dd");
        txtNsinh.setToolTipText("");
        txtNsinh.setName(""); // NOI18N
        txtNsinh.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNsinhFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNsinhFocusLost(evt);
            }
        });
        txtNsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNsinhActionPerformed(evt);
            }
        });

        txtTenLop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenLopFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenLopFocusLost(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(radnam);
        radnam.setText("Nam");

        buttonGroup1.add(radNu);
        radNu.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radnam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(radNu)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radNu)
                    .addComponent(radnam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMaLop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaLopFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaLopFocusLost(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-column.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtKhoaS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKhoaSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKhoaSFocusLost(evt);
            }
        });

        txtKhoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKhoaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKhoaFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Thêm Sinh Viên ");

        btnTSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/select-all.png"))); // NOI18N
        btnTSV.setText("Tìm Sinh Viên");
        btnTSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSVActionPerformed(evt);
            }
        });

        btnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/recurring-appointment.png"))); // NOI18N
        btnR.setText("Reset");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/change.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnTSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHten, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtMk, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtMaLop, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtKhoaS, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTenLop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtNsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(80, 80, 80))
                                    .addComponent(txtKhoa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(jLabel10)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtKhoaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnThem)
                    .addComponent(btnTSV)
                    .addComponent(btnsua)
                    .addComponent(btnR))
                .addContainerGap())
        );

        txtNsinh.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtNsinhFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNsinhFocusGained
        // TODO add your handling code here:
        if (txtNsinh.getText().equals("yyyy-mm-dd")) {
            txtNsinh.setText("");
            txtNsinh.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNsinhFocusGained

    private void txtNsinhFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNsinhFocusLost
        // TODO add your handling code here:
        if (txtNsinh.getText().equals("")) {
            txtNsinh.setText("yyyy-mm-dd");
            txtNsinh.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtNsinhFocusLost
    public boolean ktra(String s) {
        if (s.matches("[A-Z][0-9]{7}")) {
            try {
                ClsDatabase.open();
                Statement sk = ClsDatabase.con.createStatement();
                ResultSet rs = sk.executeQuery("select * from sinhvien where mssv = '" + s + "'");
                if (rs.next()) {
                    return false;
                }
                ClsDatabase.close();
            } catch (Exception e) {

            }
        } else {
            return false;
        }
        return true;
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (ktra(txtMSSV.getText())) {
            try {
                ClsDatabase.open();
                String sql = "insert into sinhvien(mssv,hten,ngaysinh,gtinh,lop,mlop,khoah,khoa,mk) values (?,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = ClsDatabase.con.prepareStatement(sql);
                ps.setString(1, txtMSSV.getText());
                ps.setString(2, txtHten.getText());
                ps.setString(3, txtNsinh.getText());
                ps.setBoolean(4, radnam.isSelected());
                ps.setString(5, txtTenLop.getText());
                ps.setString(6, txtMaLop.getText());
                ps.setString(7, txtKhoaS.getText());
                ps.setString(8, txtKhoa.getText());
                ps.setString(9, txtMk.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Thêm Thành công");
                ClsDatabase.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Thêm Sinh Viên Không thành công\nyêu cầu kiểm tra thông tin");
                e.printStackTrace();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"MSSV đã tồn tại\nHoặc sai định dạng");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtMSSVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMSSVFocusGained
        // TODO add your handling code here:
        if (txtMSSV.getText().equals("B1234567")) {
            txtMSSV.setText("");
            txtMSSV.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_txtMSSVFocusGained

    private void txtMSSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMSSVFocusLost
        // TODO add your handling code here:
        if (txtMSSV.getText().equals("")) {
            txtMSSV.setText("B1234567");
            txtMSSV.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtMSSVFocusLost

    private void txtHtenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHtenFocusGained
        // TODO add your handling code here:
        if (txtHten.getText().equals("Nguyễn Văn A")) {
            txtHten.setText("");
            txtHten.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtHtenFocusGained

    private void txtHtenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHtenFocusLost
        // TODO add your handling code here:
        if (txtHten.getText().equals("")) {
            txtHten.setText("Nguyễn Văn A");
            txtHten.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtHtenFocusLost

    private void txtTenLopFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLopFocusGained
        // TODO add your handling code here:
//        if(txtTenLop.getText().equals("Kỹ Thuật Phần Mềm")){
//            txtTenLop.setText("");
//            txtTenLop.setForeground(Color.BLACK);
//        }
    }//GEN-LAST:event_txtTenLopFocusGained

    private void txtTenLopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLopFocusLost
        // TODO add your handling code here:
//        if(txtTenLop.getText().equals("")){
//            txtTenLop.setText("Kỹ Thuật Phần Mềm");
//            txtTenLop.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_txtTenLopFocusLost

    private void txtMaLopFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLopFocusGained
        // TODO add your handling code here:
//        if(txtMaLop.getText().equals("DI1896A1")){
//            txtMaLop.setText("");
//            txtMaLop.setForeground(Color.BLACK);
//        }
    }//GEN-LAST:event_txtMaLopFocusGained

    private void txtMaLopFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLopFocusLost
        // TODO add your handling code here:
//        if(txtMaLop.getText().equals("")){
//            txtMaLop.setText("DI1896A1");
//            txtMaLop.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_txtMaLopFocusLost

    private void txtKhoaSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaSFocusGained
        // TODO add your handling code here:
//        if(txtKhoaS.getText().equals("K44")){
//            txtKhoaS.setText("");
//            txtKhoaS.setForeground(Color.BLACK);
//        }
    }//GEN-LAST:event_txtKhoaSFocusGained

    private void txtKhoaSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaSFocusLost
        // TODO add your handling code here:
//        if(txtKhoaS.getText().equals("")){
//            txtKhoaS.setText("K44");
//            txtKhoaS.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_txtKhoaSFocusLost

    private void txtKhoaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaFocusGained
        // TODO add your handling code here:
//        if(txtKhoa.getText().equals("Công Nghệ Thông Tin Và Thuyền Thông")){
//            txtKhoa.setText("");
//            txtKhoa.setForeground(Color.BLACK);
//        }
    }//GEN-LAST:event_txtKhoaFocusGained

    private void txtKhoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKhoaFocusLost
        // TODO add your handling code here:
//        if(txtKhoa.getText().equals("")){
//            txtKhoa.setText("Công Nghệ Thông Tin Và Thuyền Thông");
//            txtKhoa.setForeground(new Color(153,153,153));
//        }
    }//GEN-LAST:event_txtKhoaFocusLost

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        // TODO add your handling code here:
        res();
    }//GEN-LAST:event_btnRActionPerformed
    public void res() {
        btnThem.setEnabled(true);
        btnTSV.setEnabled(true);
        btnsua.setEnabled(false);
        txtMSSV.enable(true);
        txtHten.setText("");
        txtMSSV.setText("");
        txtNsinh.setText("");
        radnam.setSelected(true);
        txtTenLop.setText("");
        txtMaLop.setText("");
        txtKhoa.setText("");
        txtKhoaS.setText("");
        txtMk.setText("");
    }
    private void btnTSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSVActionPerformed
        // TODO add your handling code here:
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select * from sinhvien where mssv = '" + txtMSSV.getText() + "'");
            rs.next();
            txtHten.setText(rs.getString(2));
            txtNsinh.setText(rs.getString(3));
            radnam.setSelected(rs.getBoolean(4));
            txtTenLop.setText(rs.getString(5));
            txtMaLop.setText(rs.getString(6));
            txtKhoaS.setText(rs.getString(7));
            txtKhoa.setText(rs.getString(8));
            txtMk.setText(rs.getString(11));
            ClsDatabase.close();
            txtMSSV.enable(false);
            btnsua.setEnabled(true);
            btnThem.setEnabled(false);
            btnTSV.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không tìm Thấy sinh viên");
        }
    }//GEN-LAST:event_btnTSVActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        try {
            txtMSSV.enable(true);
            ClsDatabase.open();
            String sql = "update sinhvien set hten=?,ngaysinh=?,gtinh=?,lop=?,mlop=?,khoah=?,khoa=?,mk=? where mssv='" + txtMSSV.getText() + "'";
            PreparedStatement ps = ClsDatabase.con.prepareStatement(sql);
            ps.setString(1, txtHten.getText());
            ps.setString(2, txtNsinh.getText());
            ps.setBoolean(3, radnam.isSelected());
            ps.setString(4, txtTenLop.getText());
            ps.setString(5, txtMaLop.getText());
            ps.setString(6, txtKhoaS.getText());
            ps.setString(7, txtKhoa.getText());
            ps.setString(8, txtMk.getText());
            ps.executeUpdate();
            ClsDatabase.close();
            btnsua.setEnabled(false);
            btnThem.setEnabled(true);
            btnTSV.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Sửa Thành Công");
        } catch (Exception e) {
            e.printStackTrace();
        }
        res();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void txtNsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNsinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNsinhActionPerformed
    public String CheckLoi() {
        String error = "";

        return error;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnTSV;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnsua;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JRadioButton radnam;
    private javax.swing.JTextField txtHten;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtKhoaS;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMaLop;
    private javax.swing.JTextField txtMk;
    private javax.swing.JTextField txtNsinh;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
