/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Set;
import java.util.TreeMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author longs
 */
public class ThongTinSV extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinSV
     */
    public ThongTinSV() {
        initComponents();
        this.setLocation(960-this.getSize().width/2,300);
        //lbMssv.setText(this.getMssv());
        //Login l = new Login();
        //lbMssv.setText(k.getahihi());
        //this.showThongTin();
        //this.ShowNamHoc();
        //this.ShowKyHoc();
        //System.out.println(this.getMssv());
    }

    public ThongTinSV(String k) {
        initComponents();
        setMssv(k);
        this.showThongTin();
        this.ShowNamHoc();
        this.ShowKyHoc();
    }
    public String Mssv;

    public String getMssv() {
        return Mssv;
    }

    public void setMssv(String MA) {
        Mssv = MA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDxuat = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbHoten = new javax.swing.JLabel();
        lbMssv = new javax.swing.JLabel();
        lbKhoaS = new javax.swing.JLabel();
        lbGioiT = new javax.swing.JLabel();
        lbNS = new javax.swing.JLabel();
        lbLop = new javax.swing.JLabel();
        lbMLop = new javax.swing.JLabel();
        lbkhoa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cboNamHoc = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboKy = new javax.swing.JComboBox<>();
        btnLietKe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtshow = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbTcDK = new javax.swing.JLabel();
        jbDiemTB = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jbHT = new javax.swing.JLabel();
        btnIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btnDxuat.setText("Đăng xuất");
        btnDxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDxuatActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Sinh Viên"));

        jLabel2.setText("Khóa : ");

        jLabel1.setText("Họ và Tên : ");

        jLabel4.setText("MSSV : ");

        jLabel3.setText("Giới Tính : ");

        jLabel5.setText(" Khoa : ");

        jLabel6.setText("Ngày Sinh : ");

        jLabel7.setText(" Lớp :");

        jLabel8.setText("Mã Lớp :");

        lbHoten.setText("None");

        lbMssv.setText("None");

        lbKhoaS.setText("None");

        lbGioiT.setText("None");

        lbNS.setText("None");

        lbLop.setText("None");

        lbMLop.setText("None");

        lbkhoa.setText("None");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbkhoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbGioiT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbHoten))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbMssv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbKhoaS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(lbNS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbLop))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lbMLop)))
                .addContainerGap(622, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbHoten))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbMssv))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbKhoaS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbGioiT))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbNS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbLop))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbMLop))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbkhoa))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin", jPanel1);

        jLabel9.setText("Năm Học");

        cboNamHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamHocActionPerformed(evt);
            }
        });

        jLabel10.setText("Kỳ học");

        btnLietKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/select-all.png"))); // NOI18N
        btnLietKe.setText("Liệt Kê");
        btnLietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietKeActionPerformed(evt);
            }
        });

        jtshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HP", "Tên HP", "Số tín chỉ", "Mã nhóm", "Điểm số", "Điểm chữ"
            }
        ));
        jScrollPane1.setViewportView(jtshow);

        jLabel11.setText("Tống số tín chỉ đăng ký :");

        jLabel12.setText("Điểm trung bình kỳ : ");

        jbTcDK.setText("None");

        jbDiemTB.setText("None");

        jLabel13.setText("Số Tín chỉ Hoàn Thành : ");

        jbHT.setText("None");

        btnIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-file.png"))); // NOI18N
        btnIn.setText("In điểm");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLietKe)
                .addGap(27, 27, 27))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jbTcDK)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jbHT))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jbDiemTB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIn)
                .addGap(31, 31, 31))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLietKe))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIn)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jbTcDK)
                            .addComponent(jLabel13)
                            .addComponent(jbHT))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jbDiemTB))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Xem điểm", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDxuat)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(btnDxuat)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Thông tin ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ShowNamHoc() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select distinct g.namhoc from sinhvien s join diem d on s.mssv = d.mssv join giangday g on g.mnhom = d.mnhom where s.mssv = '" + this.getMssv() + "'");
            while (rs.next()) {
                String namhoc = rs.getString(1);
                cboNamHoc.addItem(namhoc);
            }
            cboNamHoc.addItem("ALL");
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ShowKyHoc() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select distinct g.kyhoc from sinhvien s join diem d on s.mssv = d.mssv join giangday g on g.mnhom = d.mnhom where s.mssv = '" + this.getMssv() + "'");
            while (rs.next()) {
                String kyhoc = rs.getString(1);
                cboKy.addItem(kyhoc);
            }
            cboKy.addItem("ALL");
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showThongTin() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select * from sinhvien s where s.mssv ='" + this.getMssv() + "'");
            rs.next();
            lbMssv.setText(rs.getString(1));
            lbHoten.setText(rs.getString(2));
            lbNS.setText(rs.getString(3));
            lbGioiT.setText(this.GT(rs.getBoolean(4)));
            lbLop.setText(rs.getString(5));
            lbMLop.setText(rs.getString(6));
            lbKhoaS.setText(rs.getString(7));
            lbkhoa.setText(rs.getString(8));
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String GT(boolean k) {
        if (k) {
            return "Nam";
        }
        return "Nữ";
    }
    private void btnDxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDxuatActionPerformed
        this.hide();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_btnDxuatActionPerformed
    public float Doi(String s) {
        if (s.equals("A")) {
            return 4f;
        }
        if (s.equals("B+")) {
            return 3.5f;
        }
        if (s.equals("B")) {
            return 3f;
        }
        if (s.equals("C+")) {
            return 2.5f;
        }
        if (s.equals("C")) {
            return 2f;
        }
        if (s.equals("D+")) {
            return 1.5f;
        }
        if (s.equals("D")) {
            return 1;
        }
        return 0;
    }
    private void cboNamHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNamHocActionPerformed

    private void btnLietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietKeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jtshow.getModel();
        tblModel.setRowCount(0);
        try {
            float TL = 0, DiemSS = 0, DK = 0;

            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            String sql ="select distinct m.mmon,m.tenmon,m.sotinchi,g.mnhom,d.so,d.chu from sinhvien s join diem d on s.mssv = d.mssv join giangday g on g.mnhom = d.mnhom join monhoc m on m.mmon = g.mmon where g.namhoc = '"+cboNamHoc.getSelectedItem().toString()+"' and g.kyhoc ='"+cboKy.getSelectedItem().toString()+"' and s.mssv = '"+getMssv()+"'" ; 
            
            if (cboNamHoc.getSelectedItem().toString().equals("ALL") && cboKy.getSelectedItem().toString().equals("ALL")) {
                sql = "select m.mmon,m.tenmon,m.sotinchi,g.mnhom,d.so,d.chu from sinhvien s join diem d on s.mssv = d.mssv join giangday g on g.mnhom = d.mnhom join monhoc m on m.mmon = g.mmon where s.mssv = '" + this.getMssv() + "'";
            } else {
                if (cboKy.getSelectedItem().toString().equals("ALL")) {
                    sql = "select distinct m.mmon,m.tenmon,m.sotinchi,g.mnhom,d.so,d.chu from sinhvien s join diem d on s.mssv = d.mssv join giangday g on g.mnhom = d.mnhom join monhoc m on m.mmon = g.mmon where g.namhoc = '"+cboNamHoc.getSelectedItem().toString()+"' and s.mssv = '"+getMssv()+"'" ;
                }
            }

            ResultSet rs = s.executeQuery(sql);
            while (rs.next()) {
                String MaHP = rs.getString(1);
                String TenHP = rs.getString(2);
                String Stc = rs.getString(3);
                String Mnhom = rs.getString(4);
                String so = rs.getString(5);
                String chu = rs.getString(6);
                DK += Float.parseFloat(Stc);
                if (!chu.equals("") && !chu.equals("F")) {
                    TL += Float.parseFloat(Stc);
                    DiemSS += Doi(chu) * Float.parseFloat(Stc);
                }
                String Data[] = {MaHP, TenHP, Stc, Mnhom, so, chu};

                tblModel.addRow(Data);
            }
            jbTcDK.setText(String.valueOf(DK));
            jbDiemTB.setText(String.valueOf((float) (DiemSS/TL)));
            jbHT.setText(String.valueOf(TL));
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLietKeActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser excelFile = new JFileChooser();
            excelFile.showSaveDialog(null);
            String str = excelFile.getSelectedFile().toString() + ".doc";
            System.out.println(str);
            File file = new File(str);
            file.createNewFile();

            //FileWriter fw = new FileWriter(file.getAbsoluteFile());
            FileOutputStream fos = new FileOutputStream(file);
            OutputStreamWriter osw = new OutputStreamWriter(fos, StandardCharsets.UTF_8);
            BufferedWriter bw = new BufferedWriter(osw);
            bw.write("MSSV : "+lbMssv.getText()+"\nHọ Và Tên : "+lbHoten.getText()+"\n\n\n");
            for (int i = 0; i < jtshow.getRowCount(); i++) {
                for (int j = 0; j < jtshow.getColumnCount(); j++) {
                    bw.write(jtshow.getModel().getValueAt(i, j).toString() + "\t");
                    System.out.printf("%-20s", jtshow.getModel().getValueAt(i, j));
                }
                System.out.print("\n");

                bw.write("\n");
            }
            
            JOptionPane.showMessageDialog(this, "Hoàn Thành");
            bw.close();
            osw.close();
            fos.close();

        } catch (Exception e) {
        }
        /*XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet ws = wb.createSheet();
        TreeMap<String,Object[]> data = new TreeMap<>();
        data.put("0",new Object[]{jtshow.getColumn(0),jtshow.getColumn(1),jtshow.getColumn(2),jtshow.getColumn(3),jtshow.getColumn(4),jtshow.getColumn(5)});
        for(int i =0; i<jtshow.getRowCount();i++){
            int k = i+1;
            data.put(""+k,new Object[]{jtshow.getValueAt(i,0).toString(),jtshow.getValueAt(i,1).toString(),jtshow.getValueAt(i,2).toString(),jtshow.getValueAt(i,3).toString(),jtshow.getValueAt(i,4).toString(),jtshow.getValueAt(i,5).toString()});
            
        }
        Set<String> ids=data.keySet();
        XSSFRow row;
        int rowID=0;
        for(String key: ids){
            row = ws.createRow(rowID++);
            Object[] values = data.get(key);
            int cellID=0;
            for(Object o: values){
                Cell cell = row.createCell(cellID++);
                cell.setCellValue(o.toString());
            }
            
        }
        try {
            JFileChooser excelFile = new JFileChooser();
            excelFile.showSaveDialog(null);
            String str = excelFile.getSelectedFile().toString()+".xlsx";
            System.out.println(str);
            File file = new File(str);
            file.createNewFile();
            FileOutputStream fos = new FileOutputStream(new File("D:/aaaa.xlsx"));
            wb.write(fos);
            fos.close();
            //
        } catch (Exception e) {
            e.printStackTrace();
        }*/
    }//GEN-LAST:event_btnInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDxuat;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLietKe;
    private javax.swing.JComboBox<String> cboKy;
    private javax.swing.JComboBox<String> cboNamHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jbDiemTB;
    private javax.swing.JLabel jbHT;
    private javax.swing.JLabel jbTcDK;
    private javax.swing.JTable jtshow;
    private javax.swing.JLabel lbGioiT;
    private javax.swing.JLabel lbHoten;
    private javax.swing.JLabel lbKhoaS;
    private javax.swing.JLabel lbLop;
    private javax.swing.JLabel lbMLop;
    private javax.swing.JLabel lbMssv;
    private javax.swing.JLabel lbNS;
    private javax.swing.JLabel lbkhoa;
    // End of variables declaration//GEN-END:variables
}
