/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlysinhvien;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author longs
 */
public class ThongTinGV extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinGV
     */
    public ThongTinGV() {
        initComponents();
        this.showThongTin();
        this.showlop();
    }

    public ThongTinGV(String k) {
        initComponents();
        setMCB(k);
        this.showThongTin();
        this.showlop();
        this.setLocation(960 - this.getSize().width / 2, 300);
    }

    public String MCB;

    public String getMCB() {
        return MCB;
    }

    public void setMCB(String MCB) {
        this.MCB = MCB;
    }

    public void showlop() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select mnhom from giangday where mcb = '" + this.getMCB() + "'");
            while (rs.next()) {
                String mnhom = rs.getString(1);
                cboLop.addItem(mnhom);
            }
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showThongTin() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select * from giaovien s where s.mcb ='" + this.MCB + "'");
            rs.next();
            lbMCB.setText(rs.getString(1));
            lbTen.setText(rs.getString(2));
            lbNS.setText(rs.getString(3));
            lbGT.setText(this.GT(rs.getBoolean(4)));
            lbKhoa.setText(rs.getString(5));
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private String GT(boolean k) {
        if (k) {
            return "Nam";
        }
        return "Nữ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTen = new javax.swing.JLabel();
        lbMCB = new javax.swing.JLabel();
        lbNS = new javax.swing.JLabel();
        lbKhoa = new javax.swing.JLabel();
        lbGT = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cboLop = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDs = new javax.swing.JTable();
        btnXemDS = new javax.swing.JButton();
        btnCN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHten = new javax.swing.JLabel();
        txtMssv = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        btnTSVLop = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jbNam = new javax.swing.JLabel();
        jbKy = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbMon = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ và tên : ");

        jLabel2.setText("Mã Cán Bộ : ");

        jLabel3.setText("Ngày Sinh : ");

        jLabel4.setText("Khoa :");

        jLabel5.setText("Giới Tính :");

        lbTen.setText("None");

        lbMCB.setText("None");

        lbNS.setText("None");

        lbKhoa.setText("None");

        lbGT.setText("None");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lbTen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lbMCB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbNS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lbKhoa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbGT)))
                .addContainerGap(492, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbTen))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbMCB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbNS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbKhoa))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbGT))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông Tin", jPanel1);

        jLabel6.setText("Lớp");

        jtDs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Và Tên", "MSSV", "Điểm số"
            }
        ));
        jtDs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDs);

        btnXemDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/select-all.png"))); // NOI18N
        btnXemDS.setText("Xem danh sách");
        btnXemDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemDSActionPerformed(evt);
            }
        });

        btnCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/change.png"))); // NOI18N
        btnCN.setText("Cập Nhật Điểm");
        btnCN.setToolTipText("");
        btnCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCNActionPerformed(evt);
            }
        });

        jLabel7.setText("Họ và Tên :");

        jLabel8.setText("MSSV :");
        jLabel8.setToolTipText("");

        jLabel9.setText("ĐIểm số ");

        txtHten.setText("None");

        txtMssv.setText("None");

        btnTSVLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-column.png"))); // NOI18N
        btnTSVLop.setText("Thêm Sinh VIên Vào Lớp");
        btnTSVLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSVLopActionPerformed(evt);
            }
        });

        jLabel10.setText("Năm Học : ");

        jLabel11.setText("Kỳ : ");

        jbNam.setText("None");

        jbKy.setText("None");

        jLabel12.setText("Môn Học : ");

        jbMon.setText("None");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXemDS)
                .addGap(18, 18, 18)
                .addComponent(btnTSVLop, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMssv))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHten))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbKy))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbNam))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbMon)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCN)
                        .addGap(76, 76, 76))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXemDS)
                        .addComponent(btnTSVLop)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jbMon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jbNam))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jbKy))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHten))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtMssv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(47, 47, 47)
                        .addComponent(btnCN)
                        .addGap(37, 37, 37))))
        );

        jTabbedPane1.addTab("Cập nhật", jPanel2);

        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuất");
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-column.png"))); // NOI18N
        btnThem.setText("Thêm Sửa Sinh Viên");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem)
                .addGap(83, 83, 83)
                .addComponent(btnDangxuat)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangxuat)
                    .addComponent(btnThem))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ShowDSLop() {
        DefaultTableModel tblModel = (DefaultTableModel) jtDs.getModel();
        tblModel.setRowCount(0);//reset view jtable
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select distinct s.hten,s.mssv,d.so from giaovien g join giangday gd on g.mcb = gd.mcb join diem d on d.mnhom = gd.mnhom join sinhvien s on s.mssv = d.mssv where g.mcb = '" + this.MCB + "' and gd.mnhom ='" + cboLop.getSelectedItem().toString() + "'");
            while (rs.next()) {
                String Hten = rs.getString(1);
                String mssv = rs.getString(2);
                String diemS = rs.getString(3);

                String Data[] = {Hten, mssv, diemS};

                tblModel.addRow(Data);
            }
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void btnXemDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemDSActionPerformed
        // TODO add your handling code here:
        this.ShowDSLop();
        this.ShowKyNam();
        txtHten.setText("");
        txtMssv.setText("");
        txtMssv.setText("");
    }//GEN-LAST:event_btnXemDSActionPerformed
    public void ShowKyNam() {
        try {
            ClsDatabase.open();
            Statement s = ClsDatabase.con.createStatement();
            ResultSet rs = s.executeQuery("select g.namhoc,g.kyhoc,m.tenmon from giangday g join monhoc m on g.mmon=m.mmon where mnhom = '" + cboLop.getSelectedItem().toString() + "'");
            rs.next();
            jbNam.setText(rs.getString(1));
            jbKy.setText(rs.getString(2));
            jbMon.setText(rs.getString(3));
            ClsDatabase.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public boolean checkDiem(String k) {
        try {
            Float s = Float.parseFloat(k);
            if (s >= 0 && s <= 10) {
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {

        }
        return false;
    }
    private void btnCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCNActionPerformed
        if (checkDiem(txtDiem.getText())) {
            try {
                ClsDatabase.open();
                String url = "update diem set so = ?,chu = ? where mssv = ? and mnhom = ? ";
                PreparedStatement ps = ClsDatabase.con.prepareStatement(url);
                ps.setFloat(1, Float.parseFloat(txtDiem.getText()));
                ps.setString(2, this.Doi(Float.parseFloat(txtDiem.getText())));
                ps.setString(3, txtMssv.getText());
                ps.setString(4, cboLop.getSelectedItem().toString());
                ps.executeUpdate();
                System.out.println("OK");
                ClsDatabase.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            this.ShowDSLop();
        } else {
            JOptionPane.showMessageDialog(this, "Điểm nhập không đúng");
        }
    }//GEN-LAST:event_btnCNActionPerformed

    public String Doi(float i) {
        String Dchu = "F";
        if (i >= 9) {
            Dchu = "A";
        } else {
            if (i >= 8) {
                Dchu = "B+";
            } else {
                if (i >= 7) {
                    Dchu = "B";
                } else {
                    if (i >= 6.5) {
                        Dchu = "C+";
                    } else {
                        if (i >= 5.5) {
                            Dchu = "C";
                        } else {
                            if (i >= 4) {
                                Dchu = "D";
                            }
                        }
                    }
                }
            }
        }

        return Dchu;
    }
    private void jtDsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDsMouseClicked
        int i = jtDs.getSelectedRow();
        TableModel model = jtDs.getModel();
        txtHten.setText(model.getValueAt(i, 0).toString());
        txtMssv.setText(model.getValueAt(i, 1).toString());
        txtDiem.setText("");
        /*if(model.getValueAt(i,2).toString().equals("")){
            txtDiem.setText("NULL");
        }
        else{
            txtDiem.setText(model.getValueAt(i,2).toString());
        }*/
    }//GEN-LAST:event_jtDsMouseClicked

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed
        this.hide();
        Login l = new Login();
        l.show();
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        //this.setVisible(false);
        ThemSV t = new ThemSV();
        t.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTSVLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSVLopActionPerformed
        ThemSVNhom N = new ThemSVNhom(cboLop.getSelectedItem().toString());

        N.setVisible(true);
    }//GEN-LAST:event_btnTSVLopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCN;
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnTSVLop;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXemDS;
    private javax.swing.JComboBox<String> cboLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jbKy;
    private javax.swing.JLabel jbMon;
    private javax.swing.JLabel jbNam;
    private javax.swing.JTable jtDs;
    private javax.swing.JLabel lbGT;
    private javax.swing.JLabel lbKhoa;
    private javax.swing.JLabel lbMCB;
    private javax.swing.JLabel lbNS;
    private javax.swing.JLabel lbTen;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JLabel txtHten;
    private javax.swing.JLabel txtMssv;
    // End of variables declaration//GEN-END:variables
}
